#!/usr/bin/env node
/**
 * price-audit.mjs — every money figure on the site, by file, with line numbers.
 *
 * Feeds the "pricing lives only on /pricing" change. Derived from source so the
 * work list cannot silently miss a page.
 *
 *   node .context/price-audit.mjs           # generate audit report
 *   node .context/price-audit.mjs --check   # strict: exit 1 on violations
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = process.cwd();
const SKIP = /^app\/(clients|api)\//;

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const full = join(dir, e);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(tsx|ts|js|mjs|txt|md)$/.test(e) && !e.endsWith('.d.ts')) out.push(relative(ROOT, full).split(sep).join('/'));
  }
  return out;
}

const files = [...walk(join(ROOT, 'app')), ...walk(join(ROOT, 'components')), ...walk(join(ROOT, 'public')), ...walk(join(ROOT, 'data'))]
  .filter(f => !SKIP.test(f) && !f.includes('node_modules') && !f.includes('.next') && !f.includes('.context/lanes'))
  .sort();

// £1,500 / £4,750 / from £15,000 / £1,200–£1,500 / £750 fixed / 20–40 hours is NOT money
// Thousands separators must be followed by three digits, so a trailing comma in prose
// ("£1,500, and if I can't find...") is not swallowed into the token.
const MONEY = /£\s?\d+(?:,\d{3})*(?:\.\d+)?\s?[km]?\b/gi;

// Figures that are evidence about a client's world, not a Decoded Ops price.
const CLIENT_COST = /150,000|10,000 |£150|£10,000/;

/**
 * --check mode. Craig's rule (8 Aug 2026): prices live on /pricing and nowhere else.
 *
 * v11 exceptions (Craig 19 Sep 2026): the following files may carry public prices:
 *   - app/pricing/page.tsx          (the canonical pricing page)
 *   - app/small-business/page.tsx   (Clarity Check £595, service "from" prices)
 *   - components/Header.tsx         (small-business mega menu sub-copy)
 *   - public/llms.txt               (machine-readable pricing lines)
 *
 * Public figures (from data/pricing-v11.json): 595, 1500, 1200, 950.
 * Forbidden figures (from data/pricing-v11.json): 720, 1440, 2880, 5760, 360,
 *   1080, 395, 995, 795, 1095, 2100, 3675, etc.
 */
const ALLOWED = new Set([
  '£1,500', '£750',                                       // confirmed price exceptions
  '£500k', '£1m', '£1.5m', '£2M', '£5m', '£7.5m',        // turnover bands, not prices
  '£150,000', '£10,000',                                  // a client's failed ERP
  '£80k',                                                 // salary comparison
  '£8,000', '£20,000',                                    // competitors' market range
  '£20k', '£40k', '£50k', '£80k',                        // industry cost ranges (infographics)
]);
const ALLOWED_FILES = new Set([
  'app/pricing/page.tsx',
  'app/small-business/page.tsx',
  'components/Header.tsx',
  'public/llms.txt',
]);

// v11: load pricing data for strict checks
let pricingData = null;
try {
  pricingData = JSON.parse(readFileSync(join(ROOT, 'data/pricing-v11.json'), 'utf8'));
} catch {}

// Forbidden words: phrase-level matches only (not substrings like "invest" → "vest")
const FORBIDDEN_WORDS_PATTERNS = [
  { pattern: /\bvests?\b/i, label: 'vest' },
  { pattern: /\bRoute [AB]\b/i, label: 'Route A/B' },
  { pattern: /\bday rate\b/i, label: 'day rate' },
  { pattern: /\bQuarterly Sprint\b/i, label: 'Quarterly Sprint' },
  { pattern: /\bDiscovery Day\b/i, label: 'Discovery Day' },
  { pattern: /\bAI Readiness Check\b/i, label: 'AI Readiness Check' },
];

// Paths that are allowed to mention "AI Readiness Check" (the free tool still exists)
const AI_READINESS_ALLOWLIST = [
  'app/tools/ai-readiness-check/',
  'app/tools/page.tsx',  // tools index + plate illustration
];

const rows = [];
for (const f of files) {
  const lines = readFileSync(join(ROOT, f), 'utf8').split(/\r?\n/);
  lines.forEach((raw, i) => {
    const hits = raw.match(MONEY);
    if (!hits) return;
    rows.push({
      file: f,
      line: i + 1,
      hits: [...new Set(hits.map(h => h.replace(/\s/g, '')))],
      isMeta: /title:|description:|openGraph|twitter:/.test(raw) || i < 30,
      isClientCost: CLIENT_COST.test(raw),
      text: raw.trim().replace(/\s+/g, ' ').slice(0, 150),
    });
  });
}

const byFile = new Map();
for (const r of rows) {
  if (!byFile.has(r.file)) byFile.set(r.file, []);
  byFile.get(r.file).push(r);
}

let out = `# Price audit — staging branch

Every money figure outside the client portal, by file. Generated by \`.context/price-audit.mjs\`.

- **${byFile.size} files** carry at least one price
- **${rows.length} lines**, ${rows.reduce((n, r) => n + r.hits.length, 0)} figures
- \`META\` = the figure is in page metadata (title/description/OG), so it shows in search results
- \`CLIENT\` = a cost from a client's story (the £150k ERP failure), not a Decoded Ops price

---
`;

for (const [file, rs] of [...byFile].sort((a, b) => b[1].length - a[1].length)) {
  out += `\n## ${file} — ${rs.length} lines\n\n`;
  for (const r of rs) {
    const tags = [r.isMeta ? 'META' : '', r.isClientCost ? 'CLIENT' : ''].filter(Boolean).join(' ');
    out += `- \`:${r.line}\`${tags ? ` **[${tags}]**` : ''} ${r.hits.join(' ')} — ${r.text}\n`;
  }
}

writeFileSync(join(ROOT, '.context/price-audit.md'), out);
console.log(`${byFile.size} files, ${rows.length} lines, ${rows.reduce((n, r) => n + r.hits.length, 0)} figures`);
for (const [file, rs] of [...byFile].sort((a, b) => b[1].length - a[1].length)) {
  console.log(`  ${String(rs.length).padStart(3)}  ${file}`);
}

if (process.argv.includes('--check')) {
  const bad = [];

  // Check 1: disallowed prices outside allowed files
  for (const r of rows) {
    if (ALLOWED_FILES.has(r.file)) continue;
    for (const h of r.hits) {
      if (!ALLOWED.has(h)) bad.push(`${r.file}:${r.line}  disallowed price ${h}  ${r.text.slice(0, 90)}`);
    }
  }

  // Check 2: v11 — forbidden_public values (only in allowed files)
  if (pricingData) {
    const forbiddenPublic = new Set((pricingData.forbidden_public || []).map(String));

    for (const r of rows) {
      if (!ALLOWED_FILES.has(r.file)) continue;
      for (const h of r.hits) {
        const numStr = h.replace(/[£,]/g, '');
        const num = parseFloat(numStr);
        if (isNaN(num)) continue;
        if (forbiddenPublic.has(String(Math.round(num)))) {
          bad.push(`${r.file}:${r.line}  forbidden_public ${h}  ${r.text.slice(0, 90)}`);
        }
      }
    }

    // Check 3: scan for forbidden words in public-facing files
    const textFiles = [...walk(join(ROOT, 'app')), ...walk(join(ROOT, 'components')), ...walk(join(ROOT, 'public'))]
      .filter(f => !SKIP.test(f) && !f.includes('node_modules') && !f.includes('.next') && !f.includes('.context/'));
    for (const f of textFiles) {
      // Allow client proposal data files (private, not public-facing)
      if (f.includes('clients/[clientId]/data/')) continue;
      const content = readFileSync(join(ROOT, f), 'utf8');
      const lines = content.split(/\r?\n/);
      for (let i = 0; i < lines.length; i++) {
        for (const { pattern, label } of FORBIDDEN_WORDS_PATTERNS) {
          if (pattern.test(lines[i])) {
            // Allow "AI Readiness Check" in the free tool and its index page
            if (label === 'AI Readiness Check' && AI_READINESS_ALLOWLIST.some(af => f.includes(af))) continue;
            bad.push(`${f}:${i + 1}  forbidden word "${label}"  ${lines[i].trim().slice(0, 90)}`);
          }
        }
      }
    }
  }

  console.log(`\ncheck: ${bad.length} violation${bad.length === 1 ? '' : ''}`);
  if (bad.length) {
    for (const b of bad) console.log(`  FAIL ${b}`);
    process.exit(1);
  }
  console.log('  PASS — all prices and content comply with v11 rules.');
}
