#!/usr/bin/env node
/**
 * price-audit.mjs — every money figure on the site, by file, with line numbers.
 *
 * Feeds the "pricing lives only on /pricing" change. Derived from source so the
 * work list cannot silently miss a page.
 *
 *   node .context/price-audit.mjs
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = process.cwd();
const SKIP = /^app\/(clients|api)\//;

function walk(dir, out = []) {
  for (const e of readdirSync(dir)) {
    const full = join(dir, e);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (/\.(tsx|ts)$/.test(e)) out.push(relative(ROOT, full).split(sep).join('/'));
  }
  return out;
}

const files = [...walk(join(ROOT, 'app')), ...walk(join(ROOT, 'components')), ...walk(join(ROOT, 'data'))]
  .filter(f => !SKIP.test(f))
  .sort();

// £1,500 / £4,750 / from £15,000 / £1,200–£1,500 / £750 fixed / 20–40 hours is NOT money
// Thousands separators must be followed by three digits, so a trailing comma in prose
// ("£1,500, and if I can't find...") is not swallowed into the token.
const MONEY = /£\s?\d+(?:,\d{3})*(?:\.\d+)?\s?[km]?\b/gi;

// Figures that are evidence about a client's world, not a Decoded Ops price.
const CLIENT_COST = /150,000|10,000 |£150|£10,000/;

/**
 * --check mode. Craig's rule (8 Aug 2026): prices live on /pricing and nowhere else.
 * Two figures survive that rule as deliberate exceptions, both confirmed by Craig:
 *   £1,500  the Clarity Audit entry anchor, load-bearing in location-page meta
 *           descriptions and the site-wide OG card
 *   £750    the App Scoping Session, the mandatory entry step for the systems line
 * Everything else below is not a Decoded Ops price at all: turnover bands that define
 * a segment, the cost of a client's failed ERP, a salary comparison, a competitor's
 * market range.
 */
const ALLOWED = new Set([
  '£1,500', '£750',                                       // confirmed price exceptions
  '£500k', '£1m', '£1.5m', '£5m', '£7.5m',                // turnover bands, not prices
  '£150,000', '£10,000',                                  // a client's failed ERP
  '£80k',                                                 // salary comparison
  '£8,000', '£20,000',                                    // competitors' market range
]);
const ALLOWED_FILES = new Set(['app/pricing/page.tsx']);

const rows = [];
for (const f of files) {
  const lines = readFileSync(join(ROOT, f), 'utf8').split(/\r?\n/);
  lines.forEach((raw, i) => {
    const hits = raw.match(MONEY);
    if (!hits) return;
    rows.push({
      file: f,
      line: i + 1,
      hits: [...new Set(hits.map(h => h.replace(/\s/g, '')))],
      isMeta: /title:|description:|openGraph|twitter:/.test(raw) || i < 30,
      isClientCost: CLIENT_COST.test(raw),
      text: raw.trim().replace(/\s+/g, ' ').slice(0, 150),
    });
  });
}

const byFile = new Map();
for (const r of rows) {
  if (!byFile.has(r.file)) byFile.set(r.file, []);
  byFile.get(r.file).push(r);
}

let out = `# Price audit — staging branch

Every money figure outside the client portal, by file. Generated by \`.context/price-audit.mjs\`.

- **${byFile.size} files** carry at least one price
- **${rows.length} lines**, ${rows.reduce((n, r) => n + r.hits.length, 0)} figures
- \`META\` = the figure is in page metadata (title/description/OG), so it shows in search results
- \`CLIENT\` = a cost from a client's story (the £150k ERP failure), not a Decoded Ops price

---
`;

for (const [file, rs] of [...byFile].sort((a, b) => b[1].length - a[1].length)) {
  out += `\n## ${file} — ${rs.length} lines\n\n`;
  for (const r of rs) {
    const tags = [r.isMeta ? 'META' : '', r.isClientCost ? 'CLIENT' : ''].filter(Boolean).join(' ');
    out += `- \`:${r.line}\`${tags ? ` **[${tags}]**` : ''} ${r.hits.join(' ')} — ${r.text}\n`;
  }
}

writeFileSync(join(ROOT, '.context/price-audit.md'), out);
console.log(`${byFile.size} files, ${rows.length} lines, ${rows.reduce((n, r) => n + r.hits.length, 0)} figures`);
for (const [file, rs] of [...byFile].sort((a, b) => b[1].length - a[1].length)) {
  console.log(`  ${String(rs.length).padStart(3)}  ${file}`);
}

if (process.argv.includes('--check')) {
  const bad = [];
  for (const r of rows) {
    if (ALLOWED_FILES.has(r.file)) continue;
    for (const h of r.hits) if (!ALLOWED.has(h)) bad.push(`${r.file}:${r.line}  ${h}  ${r.text.slice(0, 90)}`);
  }
  console.log(`\ncheck: ${bad.length} disallowed price${bad.length === 1 ? '' : 's'} outside /pricing`);
  if (bad.length) {
    for (const b of bad) console.log(`  FAIL ${b}`);
    process.exit(1);
  }
  console.log('  PASS — prices live on /pricing only, plus the £1,500 and £750 exceptions.');
}
